#pragma once
#define dfRANGE_MOVE_TOP	0
#define dfRANGE_MOVE_LEFT	0
#define dfRANGE_MOVE_RIGHT	6400
#define dfRANGE_MOVE_BOTTOM	6400

#define dfRANGE_SECTOR_RIGHT 128
#define dfRANGE_SECTOR_BOTTOM 128

#define dfRANGE_SECTOR_X (dfRANGE_MOVE_RIGHT / dfRANGE_SECTOR_RIGHT) + 2
#define dfRANGE_SECTOR_Y (dfRANGE_MOVE_BOTTOM / dfRANGE_SECTOR_BOTTOM) + 2

#define dfSPEED_PLAYER_X	6	// 3   50fps
#define dfSPEED_PLAYER_Y	4	// 2   50fps

#define dfNETWORK_PACKET_RECV_TIMEOUT	30000